DGA_CTRL = 'ckanext.ds_stats.controller.dga_controller:StatsController'
GA_API_CTRL = 'ckanext.ds_stats.controller.ga_controller:GAApiController'
GA_CTRL = 'ckanext.ds_stats.controller.ga_controller:GAController'
GAREPORT_CTRL = 'ckanext.ds_stats.controller.ga_report_controller:GaReport'
GADATASETREPORT_CTRL = 'ckanext.ds_stats.controller.ga_report_controller:GaDatasetReport'
